# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Installing dependencies
        run: sudo apt-get install -y g++ clang libc++-dev libc++abi-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              git clone --recursive https://github.com/aseprite/aseprite.git
              cd aseprite
              mkdir build
              cd build
              export CC=clang
              export CXX=clang++
              cmake \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
                -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
                -DLAF_BACKEND=skia \
                -DSKIA_DIR=$HOME/deps/skia \
                -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
                -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
                -G Ninja \
                ..
              ninja aseprite
